### ISSUE TITLE
issue in release 1.3.3

### ISSUE THREAD

**Issue by swat-agarwal** [KxSystems/embedPy#86] opened 2020-05-22 11:29 UTC
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003a70 (most recent call first):

**Comment by cmccarthy1** [comment] 2020-05-22 11:31
Have you updated both your p.q and p.so files in `%QHOME%` and `%QHOME%\w64` with the new release?

The functions that control initialisation of embedPy changes from 1.3.2 to 1.3.3

**Comment by cmccarthy1** [comment] 2020-05-22 12:43
@swat-agarwal 

We've tested the release locally with the appropriate `p.q` and `p.dll` added to the `%QHOME%` and `%QHOME%\w64` respectively and it was tested on appveyor prior to release, unfortunately we have not been able to reproduce your error.

That error generally arises from issues with multiple versions of python which are attempting to be accessed but we haven't been able to reproduce the issue locally.

Is there anything particularly unusual about your setup?

**Comment by swat-agarwal** [comment] 2020-05-23 02:44
I dont get the error with the older version of embedPy 1.3.2

**Comment by cmccarthy1** [comment] 2020-05-23 05:43
Understood, in order to debug the problem we're going to need information about how the setup was completed and your system. 

Per my previous message
> Have` you updated both your p.q and p.dll files in %QHOME% and %QHOME%\w64 with the new release?

Could you please also supply the following information about your environment

From console:
```
python3 --version
```

From a q session
```
q).z.k
q).z.K
```
Finally are you running in a virtual environment?

**Comment by swat-agarwal** [comment] 2020-05-23 09:21
Python 3.7.7

2020.05.04

No I am not running on virtual environment

**Comment by swat-agarwal** [comment] 2020-05-26 05:15
any solution to this

**Comment by cmccarthy1** [comment] 2020-05-26 06:43
We have not been able to reproduce the error to date as such cannot provide a solution as yet.

Per my message in issue #85 there should be no material difference in the operation of 1.3.2 and 1.3.3 the change between the two versions is an update to tests and the addition of support for virtual environments. Issue #85 had been due to a change in syntax for versions of tensor flow not an issue with the interface and as such is stable for use.

Once we can reproduce this error we will update this issue. Apologies for any inconvenience caused

**Comment by swat-agarwal** [comment] 2020-05-26 09:10
how can issue #85 be solved with 1.3.2

**Comment by cmccarthy1** [comment] 2020-05-26 09:16
If you replace the `tests/tensorflow.t` file that is contained in the current master branch or release `1.3.3` with the one that was contained within the `1.3.2` the tests should run with the version of tensorflow you have on your system.

**Comment by cmccarthy1** [comment] 2020-05-26 13:52
I've deleted release 1.3.3 for the time being, this bug was found with another user. This was related to a change to support virtual environments. 

I've released 1.3.4 which reverts to the embedPy code used in 1.3.2 but with the addition of the new version of `tests/tensorflow.t`

**Comment by swat-agarwal** [comment] 2020-05-26 17:14
I get the below error.I have checked and installed all requirements 
WARN: can't import: resource, remainder of tests/memory.t skipped, error was:

        import: No module named 'resource'

WARNING:tensorflow:From C:\Users\Saurabh Tikmani\Anaconda3\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-05-26 22:34:58.729498: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
These modules required for tests couldn't be imported:
        resource

try running
        pip install -r tests/requirements.txt

or with conda
        conda install --file tests/requirements.txt

failed:0, errored:0, skipped:16, total:274

**Comment by cmccarthy1** [comment] 2020-05-26 17:35
As mentioned previously the `tests/*.t` files which we're running tests are designed internal use to ensure that changes to logic don't impact functionality within our Travis and appveyor CI. It's not intended as an end to end test framework for local installs. As such if a module isn't available then you may need to install it yourself.

In this case if you don't have it available as for windows which I believe you are this module isn't available it's a Linux specific module so these tests cannot be run on your windows machine as they would not be valid.

**Comment by cmccarthy1** [comment] 2020-05-29 15:04
Given this release has been revoked and issue #87 opened to highlight the functionality addition that resulted in this issue I am closing this issue for now. If there are still issues please reopen

**Closed by cmccarthy1** 2020-05-29 15:04 UTC
