### ISSUE TITLE
windows error Specified Module could not be found

### ISSUE THREAD

**Issue by swat-agarwal** [KxSystems/embedPy#83] opened 2020-03-04 01:05 UTC
'The specified module could not be found.
  [4]  C:\q\p.q:9:
 `L`M`H`B set'@[system"python",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];C:H~B;
 .p:(`:./p 2:(`init;3))[L;H;C]]

**Comment by cmccarthy1** [comment] 2020-03-04 09:23
Hi  @swat-agarwal,

How did you install embedPy initially? Also could you please provide the output from the following

```
q)key each hsym each`$`L`M#.p
```

Once you're aware of the expected contents at these locations could you also indicate if these files exist in the locations.

**Comment by cmccarthy1** [comment] 2020-05-18 18:22
Hi @swat-agarwal 

Closing this issue for now as there isn't sufficient information to discern the cause. If you have more information which could help debug the issue please reopen and we'll be happy to help if we can.

**Closed by cmccarthy1** 2020-05-18 18:22 UTC
